---
  env:
    es6: true
    node: true
  extends: airbnb
  parser: babel-eslint
  parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
      impliedStrict: true
      jsx: true
  root: true
  rules:
    arrow-body-style:
      - error
      - as-needed
    arrow-parens: 0
    class-methods-use-this: 0
    consistent-return: 0
    constructor-super: 2
    eol-last: 0
    eqeqeq: 0
    global-require: 0
    guard-for-in: 0
    import/extensions: 0
    import/no-extraneous-dependencies: 0
    import/no-named-as-default: 0
    import/no-named-as-default-member: 0
    import/no-unresolved: 0
    max-len: 0
    new-cap: 0
    no-cond-assign:
      - error
      - except-parens
    no-inline-comments: 2
    no-param-reassign:
      - error
      - props: false
    no-restricted-syntax: 0
    no-return-assign: 0
    no-undef: 0
    no-unused-expressions:
      - error
      - allowShortCircuit: true
    no-unused-vars:
      - error
      - vars: local
        args: none
    no-use-before-define: 0
    quote-props: 0
    radix:
      - error
      - as-needed
    react/jsx-closing-bracket-location: 0
    react/jsx-filename-extension:
      - error
      - extensions:
        - .js
        - .jsx
    react/jsx-no-undef: 0
    react/no-did-mount-set-state: 0
    react/prefer-stateless-function: 0
    react/prop-types: 0
  plugins:
    - react
    - react-native